select * from "EMPLOYEES";
select * from "POSITIONS";
select * from "TEAMS";
select * from "PROJECTS";
select * from "ACTIVITY";
select * from "PROJECTS_BUGET";

--EMPLOYEES
INSERT INTO "EMPLOYEES" ("LAST_NAME", "FIRST_NAME", "PASSWORD", "EMAIL", "TEAM_N", "POSITION", "SALARY", "ACTIVE")
VALUES ('Xulescu', 'Andrei', 'xulescu567', 'andrei90@gmail.com',
		(SELECT "TEAM_NAME" from "TEAMS" where "ID_TEAM"=7),
		(SELECT "ID_POS" from "POSITIONS" where "POS_NAME"='user'), 2345, 1);
		
DELETE FROM "EMPLOYEES"
where "ID_EMPLOYEE"=2;


UPDATE "EMPLOYEES"
SET "TEAM_NAME"=(SELECT "TEAM_NAME" FROM "TEAMS" WHERE "TEAM_NAME"='test'), 
	"POSITION"=(select "ID_POS" FROM "POSITIONS" WHERE "POS_NAME"='user')
WHERE "ID_EMPLOYEE" = 2;

SELECT * FROM "EMPLOYEES"
WHERE "TEAM_N"='ROCKETS'
GROUP BY "ID_EMPLOYEE"
ORDER BY "SALARY" DESC;

SELECT E."LAST_NAME", E."FIRST_NAME", T."TEAM_NAME"
FROM "EMPLOYEES" E
LEFT JOIN "TEAMS" T ON T."TEAM_NAME"=E."TEAM_N"
ORDER BY T."TEAM_NAME", E."LAST_NAME", E."FIRST_NAME";


--POSITIONS
Insert into "POSITIONS"("POS_NAME") 
values('manager'),
('user');

INSERT INTO "POSITIONS"("POS_NAME")
values('POSITION');

--TEAMS
BEGIN;
INSERT INTO "TEAMS"("TEAM_NAME", "TEAM_MANAGER")
VALUES('BLUETECH',
	  (SELECT "ID_EMPLOYEE" FROM "EMPLOYEES" WHERE "ID_EMPLOYEE"=7));
UPDATE "EMPLOYEES"
SET "POSITION"=(SELECT "ID_POS" FROM "POSITIONS" WHERE "POS_NAME"='manager'), 
"TEAM_N"=(SELECT "TEAM_NAME" FROM "TEAMS" WHERE "TEAM_NAME"='BLUETECH') 
WHERE "ID_EMPLOYEE"=7;
COMMIT;
ROLLBACK;

UPDATE "TEAMS"
SET "TEAM_MANAGER"=(SELECT "ID_EMPLOYEE" FROM "EMPLOYEES" WHERE "ID_EMPLOYEE"=)

BEGIN;
UPDATE "EMPLOYEES"
SET "POSITION"=(SELECT "ID_POS" FROM "POSITIONS" WHERE "POS_NAME"='user'), 
"TEAM_N"=NULL 
FROM "TEAMS" 
WHERE "ID_EMPLOYEE" = "TEAMS"."TEAM_MANAGER" AND "ID_EMPLOYEE"=2;
DELETE FROM "PROJECTS" WHERE "TEAM"='ROCKETS';
DELETE FROM "TEAMS" WHERE "TEAM_NAME"='ROCKETS';
COMMIT;
ROLLBACK;

--PROJECTS
INSERT INTO "PROJECTS" ("PROJECT_NAME", "TEAM", "TERM_START", "TERM_END")
SELECT 'dashboard', "TEAM_NAME", CURRENT_DATE, CURRENT_DATE+INTERVAL'30 DAYS' 
FROM "TEAMS" WHERE "TEAM_NAME"='BLUETECH';

UPDATE "PROJECTS"
SET "PROJECT_STATUS"='IN WORK'
WHERE "ID_PROJECT"=2;

BEGIN;
DELETE FROM "PROJECTS" WHERE "PROJECT_NAME"='nume_proiect';
COMMIT;
ROLLBACK;


--ACTIVITATE
INSERT INTO "ACTIVITY" ("ID_EMP", "ID_PROJ", "HOURS_WORKED", "OVERTIME")
SELECT E."ID_EMPLOYEE", P."ID_PROJECT", 10.55, 1.05 FROM "EMPLOYEES" E
JOIN "PROJECTS" P
ON E."TEAM_N"=P."TEAM"
WHERE E."ID_EMPLOYEE"=2;

BEGIN
DELETE FROM "ACTIVITY" WHERE "ID_ACT"=2;
COMMIT;
ROLLBACK;	  