CREATE TABLE "EMPLOYEES"(
	"ID_EMPLOYEE" INT GENERATED ALWAYS AS identity(START WITH 1 INCREMENT BY 1) NOT NULL primary key,
	"LAST_NAME" varchar(20) NOT NULL,
	"FIRSLT NAME" varchar(40) NOT NULL,
	"EMAIL" varchar(30) NOT NULL,
	"TEAM_N" varchar(40),
	"POSITION" int,
	"SALARY" float8,
	"PASSWORD" VARCHAR(40),
	"ACTIVE" INT
);

ALTER TABLE  "EMPLOYEE" 
ADD "SALARY" float8 default 0.0,
ADD CONSTRAINT "POSITIVE_CHECK" CHECK ("SALARY">=0);

SELECT * FROM "EMPLOYEES";

ALTER TABLE "EMPLOYEES"
ALTER COLUMN "POSITION" TYPE int using "POSITION"::integer;

ALTER TABLE "EMPLOYEES"
ADD CONSTRAINT "FK_TEAM"
FOREIGN KEY ("TEAM_N")
REFERENCES TEAMS(TEAM_NAME);

INSERT INTO "EMPLOYEES" ("LAST_NAME", "FIRST_NAME", "PASSWORD", "EMAIL", "TEAM_N", "POSITION")
VALUES ('test', 'test', 'test1', 'test@gmail.com', (SELECT "TEAM_N" from echipe where "ID_TEAM"=3),
		(SELECT "ID_POS" from "POSITIONS" where "POS_NAME"='user'));

ALTER TABLE "EMPLOYEES"
ADD CONSTRAINT "FK_POS"
FOREIGN KEY ("POSITION")
REFERENCES "POSITIONS"("ID_POS");

ALTER TABLE "EMPLOYEES"
ADD COLUMN "PASSWORD" varchar(30) NOT NULL DEFAULT 'parola123';

------------
CREATE TABLE "POSITIONS"(
	"ID_POS" int not null primary key GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
	"POS_NAME" varchar(40) not null
)

Insert into "POSITIONS"("POS_NAME") values
('manager'),
('user');

SELECT * FROM "POSITIONS";

----------------------------------
CREATE TABLE "teams"(
	"ID_TEAM" int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
	"TEAM_NAME" varchar(20) not null,
	"TEAM_MANAGER" int not null,
)

-----
ALTER TABLE "TEAMS"
ALTER COLUMN "TEAM_MANAGER" TYPE INT USING "TEAM_MANAGER"::integer;

-------
ALTER TABLE "TEAMS"
ADD CONSTRAINT "FK_MANAGER"
FOREIGN KEY ("TEAM_MAANGER")
REFERENCES "EMPLOYEES"("ID_EMPLOYEE");
-------
ALTER TABLE "EMPLYEES"
	ADD CONSTRAINT "UNIQUE_MANAGER" UNIQUE ("TEAM_MANAGER");
	
-------
ALTER TABLE "TEAMS"
DROP CONSTRAINT ... CASCADE;

-----
ALTER TABLE "TEAMS"
ADD CONSTRAINT "PK_TEAM_NAME" PRIMARY KEY ("TEAM_NAME");
-----
SELECT * FROM "TEAMS";


----
CREATE TABLE "PROJECTS"(
  "ID_PROJECT" INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
  "PROJECT_NAME" VARCHAR(20) NOT NULL,
  "TEAM" varchar(30),
  "PROJECT_STATUS" VARCHAR(30) NOT NULL DEFAULT 'IN LUCRU'
);

DELETE FROM "PROJECTS"
where "ID_PROJECT"=1;

DELETE FROM "ACTIVITY";

SELECT * FROM "PROJECTS";

ALTER TABLE "PROJECTS"
ADD "TERM_START" date,
ADD "TERM_END" date,
ADD CONSTRAINT "TERM_START_CHECK" CHECK ("TERM_START">=CURRENT_DATE),
ADD CONSTRAINT termen_final_check CHECK ("TERM_END">=CURRENT_DATE);

ALTER TABLE "PROJECTS"
ADD CONSTRAINT "FK_TEAM"
FOREIGN KEY ("TEAM")
REFERENCES "TEAMS"("ID_TEAM");

----------
CREATE TABLE "POJECTS_BUDGET"(
	"ID_PROJECT_BUDGET" INT PRIMARY KEY GENERATED ALWAYS AS identity(START WITH 1 INCREMENT BY 1) NOT NULL,
	"TOTAL_BUDGET" float8,
	"BUDGET_SPENT" float8
);

ALTER TABLE "PROJECTS_BUDGET"
ADD CONSTRAINT "FK_ID_PB"
FOREIGN KEY ("ID_PROJECT_BUDGET")
REFERENCES "PROJECTS"("ID_PROJECT");

CREATE TABLE "ACTIVITY"(
	"ID_ACT" int NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"ID_EMP" int not null,
	"ID_PROJ" int NOT NULL,
	"HOURS_WORKED" float4,
	"OVERTIME" float4 
);

SELECT * FROM "ACTIVITY";

ALTER TABLE "ACTIVITY"
ADD CONSTRAINT "FK_PROJECT"
FOREIGN KEY ("ID_PROJ")
REFERENCES "PROJECTS"("ID_PROJECT");

ALTER TABLE "ACTIVITY"
ADD CONSTRAINT "FK_EMP"
FOREIGN KEY ("ID_EMP")
REFERENCES "EMPLOYEES"("ID_EMPLOYEE");

ALTER TABLE "ACTIVITY"
ADD COLUMN "DAY" DATE NOT NULL DEFAULT CURRENT_DATE;

------------
SELECT "ID_TEAM", "TEAM_NAME",
       (SELECT count(*) FROM "EMPLOYEES" WHERE "TEAM_N"="TEAMS"."TEAM_NAME") AS "NUMBER OF USERS"
FROM "TEAMS";

---------
SELECT "ID_PROJECT_BUDGET", "TOTAL_BUDGET", "BUDGET_SPENT", ("TOTAL_BUDGET"-"BUDGET_SPENT") AS "BUDGET_LEFT"
FROM "PROJECTS_BUDGET";

ALTER TABLE "EMPLOYEES"
ADD COLUMN "ACTIVE" INT NOT NULL DEFAULT 1,
ADD CONSTRAINT "STATUS_CHECK" CHECK ("ACTIVE" IN (0, 1));

ALTER TABLE "ACTIVITY"
ADD COLUMN "ACTIVE" INT NOT NULL DEFAULT 1
ADD CONSTRAINT "STATUS" CHECK (STATUS IN (0, 1));

SELECT * FROM "POSITIONS";








